openapi: 3.0.0
info:
  title: Seat Service API
  description: API cho dịch vụ quản lý ghế và trạng thái đặt chỗ
  version: 1.0.0
servers:
  - url: http://localhost:8082
    description: Local Development Server
  - url: http://seat-service:8082
    description: Docker Development Environment

tags:
  - name: seats
    description: Quản lý ghế và trạng thái đặt chỗ
  - name: operations
    description: Các thao tác với ghế (đặt, giải phóng)

paths:
  /api/seats/{showtimeId}/{seatNumber}:
    get:
      summary: Lấy thông tin chi tiết của một ghế theo lịch chiếu và số ghế
      tags:
        - seats
      parameters:
        - name: showtimeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID của lịch chiếu
        - name: seatNumber
          in: path
          required: true
          schema:
            type: string
          description: Số ghế (ví dụ A1, B2)
      responses:
        '200':
          description: Thông tin ghế được trả về thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeatDTO'
        '404':
          description: Không tìm thấy ghế

  /api/seats/{showtimeId}/available:
    get:
      summary: Lấy danh sách các ghế còn trống cho một lịch chiếu
      tags:
        - seats
      parameters:
        - name: showtimeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID của lịch chiếu
      responses:
        '200':
          description: Danh sách ghế còn trống được trả về thành công
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SeatDTO'

  /api/seats/reserve/{showtimeId}/{seatNumber}:
    post:
      summary: Đặt ghế
      tags:
        - operations
      parameters:
        - name: showtimeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID của lịch chiếu
        - name: seatNumber
          in: path
          required: true
          schema:
            type: string
          description: Số ghế (ví dụ A1, B2)
      responses:
        '200':
          description: Ghế được đặt thành công
          content:
            application/json:
              schema:
                type: string
                example: "Seat reserved successfully"
        '409':
          description: Ghế đã được đặt hoặc không khả dụng
          content:
            application/json:
              schema:
                type: string
                example: "Seat is already reserved or unavailable"

  /api/seats/release:
    post:
      summary: Giải phóng ghế đã đặt
      tags:
        - operations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SeatDTO'
      responses:
        '200':
          description: Ghế được giải phóng thành công
          content:
            application/json:
              schema:
                type: string
                example: "Seat released successfully"
        '400':
          description: Không thể giải phóng ghế
          content:
            application/json:
              schema:
                type: string
                example: "Failed to release seat"

components:
  schemas:
    Seat:
      type: object
      properties:
        id:
          type: integer
          format: int64
        seatNumber:
          type: string
          example: "A1"
        reserved:
          type: boolean
        showtime:
          $ref: '#/components/schemas/Showtime'

    SeatDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        seatNumber:
          type: string
          example: "A1"
        reserved:
          type: boolean
        showtimeId:
          type: integer
          format: int64

    Showtime:
      type: object
      properties:
        id:
          type: integer
          format: int64
        time:
          type: string
          format: date-time
        theater:
          type: string
        movie:
          $ref: '#/components/schemas/Movie'
        seats:
          type: array
          items:
            $ref: '#/components/schemas/Seat'
        bookings:
          type: array
          items:
            $ref: '#/components/schemas/Booking'

    Movie:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string

    Booking:
      type: object
      properties:
        id:
          type: integer
          format: int64
        seatNumber:
          type: string
        customerName:
          type: string
        email:
          type: string
        paid:
          type: boolean
        showtime:
          $ref: '#/components/schemas/Showtime'