CREATE DATABASE IF NOT EXISTS booking_db;
CREATE DATABASE IF NOT EXISTS seat_db;
CREATE DATABASE IF NOT EXISTS movie_db;

CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON booking_db.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON seat_db.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON movie_db.* TO 'user'@'%';
FLUSH PRIVILEGES;