server:
  port: 8083

spring:
  application:
    name: booking-service
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://mysql:3306/booking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root  # Thay bằng username MySQL của bạn
    password: root  # Thay bằng password MySQL của bạn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: booking-service-group

  mail:
    host: smtp.gmail.com
    port: 587
    username: ledinhduong802@gmail.com
    password: qaeb styo dzvp bslf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

seat-service:
  url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
movie-service:
  url: http://localhost:8081

#showtime-service:
#  url: http://localhost:8082


resilience4j:
  circuitbreaker:
    instances:
      bookingService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  ratelimiter:
    instances:
      bookingAPI:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 0

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: full
