server:
  port: 8083

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/booking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root  # Thay bằng username MySQL của bạn
    password: root  # Thay bằng password MySQL của bạn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: booking-service-group

  mail:
    host: smtp.gmail.com
    port: 587
    username: ledinhduong802@gmail.com
    password: qaeb styo dzvp bslf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      bookingService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  ratelimiter:
    instances:
      bookingAPI:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 0

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: full
