server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**, /api/payment/**
        - id: seat-service
          uri: lb://seat-service
          predicates:
            - Path=/api/seats/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
jwt:
  secret: your-secret-key
