server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
        - id: seat-service
          uri: lb://seat-service
          predicates:
            - Path=/api/seats/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: your-secret-key
