
spring:
#  datasource:
#    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12776038
#    username: sql12776038
#    password: BEFHYIHKNs
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/demomicro
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672

server:
  port: 8080

